require( 'sinatra' )
require( 'sinatra/contrib/all' )
require( 'pry-byebug' )
require_relative('./models/game')
require_relative('./controllers/game_controller')
require_relative('./controllers/athlete_controller')
require_relative('./controllers/event_controller')
require_relative('./controllers/participation_controller')